NAMELESS-docker
R-accoo-n/Nameless-volunteer-project pull request #12
Opened 2023-03-07 01:31 UTC by nazardyda

NAMELESS-docker add Dockerifle, docker-compose.yml, run file

2023-03-07 01:32 UTC, R-accoo-n commented
|File|Coverage [0%]|:x:|
|:-|:-:|:-:|
|[FundraisingType.java](https://github.com/R-accoo-n/Nameless-volunteer-project/blob/52ce44192faf7eee813a6d8be41c6d09676c9153/src%2Fmain%2Fjava%2Fcom%2Fnameless%2Fvolunteerproject%2Fenums%2FFundraisingType.java)|0%|:x:|
|[UserRole.java](https://github.com/R-accoo-n/Nameless-volunteer-project/blob/52ce44192faf7eee813a6d8be41c6d09676c9153/src%2Fmain%2Fjava%2Fcom%2Fnameless%2Fvolunteerproject%2Fenums%2FUserRole.java)|0%|:x:|
|[User.java](https://github.com/R-accoo-n/Nameless-volunteer-project/blob/52ce44192faf7eee813a6d8be41c6d09676c9153/src%2Fmain%2Fjava%2Fcom%2Fnameless%2Fvolunteerproject%2Fmodels%2FUser.java)|0%|:x:|
|[Fundraising.java](https://github.com/R-accoo-n/Nameless-volunteer-project/blob/52ce44192faf7eee813a6d8be41c6d09676c9153/src%2Fmain%2Fjava%2Fcom%2Fnameless%2Fvolunteerproject%2Fmodels%2FFundraising.java)|0%|:x:|

|Total Project Coverage|0%|:x:|
|:-|:-:|:-:|

2023-03-07 11:37 UTC, R-accoo-n requested changes
At Dockerfile add after 3rd line in new line RUN cd /project ; ./mvnw clean package

2023-03-08 05:04 UTC, nazardyda commented
./mvnw clean package couldn't be add at Dockerfile because the program drop down. I think we can fix it later or we can make meet where discuss and solve this problem

2023-03-08 11:59 UTC, R-accoo-n approved these changes

2023-03-08 11:59 UTC, merged